name: Frontend CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [karsajobs-ui]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/
      - run: hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker build -t ghcr.io/${{ github.actor }}/karsajobs-ui:latest .
      - run: docker push ghcr.io/${{ github.actor }}/karsajobs-ui:latest
