name: Frontend CI

on:
  push:
    branches: [karsajobs-ui]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y hadolint
      - run: hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker build -t ghcr.io/${{ github.actor }}/karsajobs-ui:latest .
      - run: docker push ghcr.io/${{ github.actor }}/karsajobs-ui:latest
